GET http://localhost:5000/api/v1/todos
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5URCIsImlhdCI6MTY0OTI0NDI0MywiZXhwIjoxNjQ5MjQ0Mjg4fQ.uD15_6o8sTwwLDPkV7oDZwoffWucpyJNXGAoPoWEeEs
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "NTD"
}